/*
 * ProductAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www;

import com.example.www.controllers.*;
import com.example.www.http.client.HttpClient;

public class ProductAPIClient {
    /**
     * Singleton access to Product controller
     * @return	Returns the ProductController instance 
     */
    public ProductController getProduct() {
        return ProductController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public ProductAPIClient() {
    }

}